=== Seb732/projektJZ/schemaMenu2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="menu_restauracji">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kategoria" maxOccurs="unbounded"/>
        <xs:element ref="napoje"/>
        <xs:element ref="dodatki"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="kategoria">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="danie" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="nazwa" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="danie">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nazwa" type="xs:string"/>
        <xs:element ref="skladniki"/>
      </xs:sequence>
      <xs:attribute name="cena" type="xs:decimal" use="required"/>
      <xs:attribute name="na_wagę" type="xs:string" use="optional"/>
      <xs:attribute name="typ" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="skladniki">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="skladnik" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="napoje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="napój" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="nazwa" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="napój">
    <xs:complexType mixed="true">
      <xs:attribute name="cena" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dodatki">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dodatek" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="nazwa" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dodatek">
    <xs:complexType mixed="true">
      <xs:attribute name="cena" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Seb732/projektJZ/menuRestauracji.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:/C:/Users/user/Downloads/style_menu2.xsl"?>
<menu_restauracji xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/user/Downloads/schemaMenu2.xsd">
    <kategoria nazwa="Przystawki">
      <danie typ="wegetariańskie" cena="18" na_wagę="NIE">
          <nazwa>Carpaccio z pieczonych burakow</nazwa>
          <skladniki>
            <skladnik>Buraki</skladnik>
            <skladnik>Orzechy</skladnik>
            <skladnik>Ser kozi</skladnik>
          </skladniki>
      </danie>
    </kategoria>
    <kategoria nazwa="Dania główne">
      <danie typ="mięsne" cena="25" na_wagę="NIE">
         <nazwa>Rolada śląska</nazwa>
         <skladniki>
           <skladnik>Wieprzowina</skladnik>
            <skladnik>Ogorek</skladnik>
         </skladniki>
      </danie>
      <danie typ="ryby i owoce morza" cena="20" na_wagę="NIE">
          <nazwa>Filet z łososia</nazwa>
          <skladniki>
            <skladnik>Łosoś</skladnik>
            <skladnik>Ziemniaki</skladnik>
          </skladniki>
      </danie>
      <danie typ="makarony" cena="16" na_wagę="NIE">
        <nazwa>Rigatoni</nazwa>
        <skladniki>
          <skladnik>Sos pomidorowy</skladnik>
          <skladnik>Czosnek</skladnik>
        </skladniki>
      </danie>
    </kategoria>
    <kategoria nazwa="Zupy">
        <danie cena="7">
          <nazwa>Zupa pomidorowa</nazwa>
          <skladniki>
            <skladnik>Pomidory</skladnik>
            <skladnik>Czosnek</skladnik>
          </skladniki>
        </danie>
    </kategoria>
    <kategoria nazwa="Desery">
        <danie cena="14">
          <nazwa>Tiramisu</nazwa>
          <skladniki>
            <skladnik>Biszkopt</skladnik>
            <skladnik>Espresso</skladnik>
            <skladnik>Ser Mascarpone</skladnik>
          </skladniki>
        </danie>
    </kategoria>
    <napoje nazwa="Napoje">
      <napój cena="5">Kawa</napój>
      <napój cena="4">Herbata</napój>
    </napoje>
    <dodatki nazwa="Dodatki">
      <dodatek cena="7">Frytki</dodatek>
      <dodatek cena="11">Sałatka cezar</dodatek>
    </dodatki>
</menu_restauracji>
